{% set name = "dadi-cli" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dadi_cli-{{ version }}.tar.gz
  sha256: 291088b9163e52d30bc86162cf65fc49f3306f715af92f12cef06763265c1a91

build:
  entry_points:
    - dadi-cli = dadi_cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - hatchling
    - pip
  run:
    - python >=3.6
    - dadi

test:
  imports:
    - dadi_cli
  commands:
    - dadi-cli --help
    - dadi-cli GenerateFs --help
    - dadi-cli InferDM --help
    - dadi-cli InferDFE --help
    - dadi-cli SimulateDM --help
    - dadi-cli SimulateDFE --help
    - dadi-cli GenerateCache --help
    - dadi-cli StatDM --help
    - dadi-cli StatDFE --help
    - dadi-cli Plot --help
    - dadi-cli BestFit --help
    - dadi-cli Model --help
    - dadi-cli Pdf --help

  requires:
    - pip

about:
  home: https://github.com/xin-huang/dadi-cli
  summary: A command line interface for dadi
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/xin-huang/dadi-cli#dadi-cli

extra:
  recipe-maintainers:
    - xin-huang
    - tjstruck
    - RyanGutenkunst
