{% set name = "dadi-cli" %}
{% set version = "0.9.13" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dadi_cli-{{ version }}.tar.gz
  sha256: 9ab125071b944eb82fb5812e80bb5d0c6692577f4423c7f2bd8b5d6bd0f189b2

build:
  entry_points:
    - dadi-cli = dadi_cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - dadi

test:
  imports:
    - dadi_cli
  commands:
    - dadi-cli --help
    - dadi-cli GenerateFs --help
    - dadi-cli InferDM --help
    - dadi-cli InferDFE --help
    - dadi-cli SimulateDM --help
    - dadi-cli SimulateDFE --help
    - dadi-cli GenerateCache --help
    - dadi-cli StatDM --help
    - dadi-cli StatDFE --help
    - dadi-cli Plot --help
    - dadi-cli BestFit --help
    - dadi-cli Model --help
    - dadi-cli Pdf --help

  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/xin-huang/dadi-cli
  summary: A command line interface for dadi
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/xin-huang/dadi-cli#dadi-cli

extra:
  recipe-maintainers:
    - xin-huang
    - tjstruck
    - RyanGutenkunst
